name: Publish to nuget

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: build, pack and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to NuGet
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: Serilog.Sinks.Slack/Serilog.Sinks.Slack.csproj
        NUGET_KEY: ${{secrets.NUGET_KEY}}
